name = "pkglens"
compatibility_date = "2026-06-25"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "pkglens"
database_id = "9039d898-a0bc-4831-a84b-abe256f499df"
migrations_dir = "migrations"
